name: Build Image
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      docker_hub_token:
        required: true
    outputs:
      image:
        value: cheetah26/web-server:${{ inputs.tag }}
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: cheetah26
          password: ${{ secrets.docker_hub_token }}
      - uses: docker/build-push-action@v6
        with:
          context: ./web-server
          tags: cheetah26/web-server:${{ inputs.tag }}
          push: true
