name: Release
on:
  push:
    tags:
      - v**
jobs:
  build-image:
    uses: ./.github/workflows/build-image.yml
    with:
      tag: ${{ github.ref_name }}
    secrets:
      docker_hub_token: ${{ secrets.DOCKER_HUB_PAT }}
